my_blog/my_blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.defaults import page_not_found

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stories.urls')),
    path('users/', include(('users.urls', 'users'), namespace="users")),
    path("__debug__/", include("debug_toolbar.urls")),
]
# when DEBUG is False(production): tells Django to take OUR view 'page_not_found' for non-existent pages
handler404 = page_not_found

admin.site.site_header = 'Админ-панель Django сайта'
admin.site.index_title = 'Админ-панель сайта с рассказами'


# when DEBUG is True, we have one more URL (to downloaded files) for test server to take these
# files on MEDIA_URL and view on HTML page
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/users/urls.py
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy

from . import views
from .views import UserPasswordChange

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('register_done/', views.register_done, name='register-done'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('password-change/', UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(
                                              template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password-reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                                      email_template_name='users/password_reset_email.html',
                                                      success_url=reverse_lazy('users:password_reset_done')
                                                      ), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(
                                           template_name='users/password_reset_done.html'
                                                              ),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
                                            template_name='users/password_reset_confirm.html',
                                            success_url=reverse_lazy('users:password_reset_complete')
                                                                           ),
         name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(
                                          template_name='users/password_reset_complete.html'
                                                                     ),
         name='password_reset_complete')
]

my_blog/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.

class User(AbstractUser):
    """New model of User with some additional fields"""
    photo = models.ImageField(upload_to="users/%Y/%m/%d/", blank=True, null=True, verbose_name="Фотография")
    date_birth = models.DateTimeField(blank=True, null=True, verbose_name="Дата рождения")

my_blog/users/forms.py
import datetime as dt

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm


class LoginUserForm(AuthenticationForm):
    """A form to log in the user with corresponding fields"""
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    """A form to register the user with corresponding fields and self-made validators for field 'password2' and
    'email' """
    username = forms.CharField(label="Логин", widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label="Пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label="Повтор пароля", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {'email': 'E-mail',
                  'first_name': 'Имя',
                  'last_name': 'Фамилия'}
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }

    def clean_email(self):
        if get_user_model().objects.filter(email=self.cleaned_data['email']).exists():
            raise forms.ValidationError('Такой email уже существует')
        return self.cleaned_data['email']

    def clean_password2(self):
        if self.cleaned_data['password1'] != self.cleaned_data['password2']:
            raise forms.ValidationError('Пароли на совпадают')
        return self.cleaned_data['password1']


class ProfileUserForm(forms.ModelForm):
    """A form with the user's profile with corresponding fields"""
    username = forms.CharField(disabled=True, label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(disabled=True, label="E-mail", widget=forms.TextInput(attrs={'class': 'form-input'}))
    this_year = dt.date.today().year
    date_birth = forms.DateField(widget=forms.SelectDateWidget(years=tuple(range(this_year - 100, this_year - 5))))

    class Meta:
        model = get_user_model()
        fields = ['photo', 'username', 'date_birth', 'email', 'first_name', 'last_name']
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }


class UserPasswordChangeForm(PasswordChangeForm):
    """A form to set a new password and repeat it with corresponding fields"""
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение пароля",
                                    widget=forms.PasswordInput(attrs={'class': 'form-input'}))

my_blog/users/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView
from .forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm
from my_blog.settings import DEFAULT_USER_IMAGE


# Create your views here.
class LoginUser(LoginView):
    """"A class based view to log in for non-authorized users"""
    # or simply AuthenticationForm(works together with LoginView)
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}


def logout_user(request):
    """A view to log out for authorized users"""
    # logging out and redirection to log in
    logout(request)
    return HttpResponseRedirect(reverse('users:login'))


class RegisterUser(CreateView):
    """"A class based view to register"""
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': 'Регистрация'}
    success_url = reverse_lazy('users:register-done')


def register_done(request):
    """A view that displays register-done-page"""
    return render(request, 'users/register_done.html', context={'title': 'Добро пожаловать!'})


class ProfileUser(LoginRequiredMixin, UpdateView):
    """"A class based view to show and update user's profile"""
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': 'Профиль пользователя',
                     'default_image': DEFAULT_USER_IMAGE}

    def get_success_url(self):
        # after changing and saving an updated profile
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        # getting a profile to update - only CURRENT profile
        return self.request.user


class UserPasswordChange(PasswordChangeView):
    """"A class based view to update user's password"""
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy('users:password_change_done')
    template_name = 'users/password_change_form.html'

my_blog/users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<h1>Авторизация</h1>

<form method="POST">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}"/>
    <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
            <p><label for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
    <p><button type="submit">Войти</button></p>
    <p><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>
</form>
{% endblock%}

my_blog/users/templates/users/password_change_done.html
{% extends 'base.html' %}
<h1>Пароль успешно изменен!</h1>

<p>Вы успешно изменили пароль.
  <a href="{% url 'users:profile' %}">Вернуться в профиль</a>
</p>

my_blog/users/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Изменение пароля</h1>

<form method="POST">
    {% csrf_token %}

    <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
            <p><label for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
    <p><button type="submit">Сохранить</button></p>
</form>

{% endblock%}

my_blog/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
<h1>Пароль изменен</h1>

<p>Поздравляем! Вы успешно изменили пароль своего аккаунта.
  Используйте его для <a href="{% url 'users:login' %}">входа в систему</a>.</p>

{% endblock %}

my_blog/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
<h1>Новый пароль</h1>

<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p><button type="submit">Сохранить</button></p>
</form>

{% endblock %}

my_blog/users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}


{% block content %}
<h1>Сброс пароля</h1>
<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

my_blog/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

my_blog/users/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
<h1>Восстановление пароля</h1>

<form method="post">
    {% csrf_token %}
    {% for f in form %}
      <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
      <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p><button type="submit">Сбросить по E-mail</button></p>
</form>

{% endblock %}

my_blog/users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
<h1>{{title}}</h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    {% if user.photo %}
      <p><img src="{{ user.photo.url }}">
    {% else %}
        <p><img src="{{ default_image }}">
    {% endif %}

    <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
            <p><label for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
    <p><button type="submit">Сохранить</button></p>
</form>

<hr>
<p><a href="{% url 'users:password_change' %}">Сменить пароль</a></p>
{% endblock%}

my_blog/users/templates/users/register.html
{% extends 'base.html' %}
{% block content %}
<h1>{{title}}</h1>

<form method="POST">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}"/>
    <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
            <p><label for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
    <p><button type="submit">Регистрация</button></p>
</form>
{% endblock%}

my_blog/users/templates/users/register_done.html
{% extends 'base.html' %}
{% block content %}
<h1>{{title}}</h1>

<p>Вы успешно зарегистрировались. Войдите по <a href="{% url 'users:login' %}">ссылке</a>.</p>
{% endblock%}