my_blog/my_blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.defaults import page_not_found

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stories.urls')),
    path('users/', include(('users.urls', 'users'), namespace="users")),
    path("__debug__/", include("debug_toolbar.urls")),
]
# when DEBUG is False(production): tells Django to take OUR view 'page_not_found' for non-existent pages
handler404 = page_not_found

admin.site.site_header = 'Админ-панель Django сайта'
admin.site.index_title = 'Админ-панель сайта с рассказами'


# when DEBUG is True, we have one more URL (to downloaded files) for test server to take these
# files on MEDIA_URL and view on HTML page
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_blog/users/urls.py
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy

from . import views
from .views import UserPasswordChange

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('register_done/', views.register_done, name='register-done'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('password-change/', UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(
                                              template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password-reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                                      email_template_name='users/password_reset_email.html',
                                                      success_url=reverse_lazy('users:password_reset_done')
                                                      ), name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(
                                           template_name='users/password_reset_done.html'
                                                              ),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
                                            template_name='users/password_reset_confirm.html',
                                            success_url=reverse_lazy('users:password_reset_complete')
                                                                           ),
         name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(
                                          template_name='users/password_reset_complete.html'
                                                                     ),
         name='password_reset_complete')
]

my_blog/templates/base.html
{% load static %}
{% load stories_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link type="text/css" rel="stylesheet" href="{% static 'stories/css/styles.css' %}"/>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>{{title}}</title>
</head>
<body>

<table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>
{% block mainmenu %}
    <div class="header">
		<ul id="mainmenu" class="mainmenu">
			<li class="logo">
				<a href="{% url 'index' %}">
					<img src="{% static 'stories/images/logo.jpg' %}" height=70px width=60px>
					<div></div>
				</a>
			</li>

			{% for m in mainmenu %}
				<li><a href="{% url m.url_name %}">{{m.title}}</a></li>
			{% endfor %}

			{% if user.is_authenticated %}
				<li class="last"><a href="{% url 'users:profile' %}">{{user.username}}</a> |
					<a href="{% url 'users:logout' %}">Выйти</a></li>
			{% else %}
    			<li class="last"><a href="{% url 'users:login' %}">Войти</a> |
					<a href="{% url 'users:register' %}">Регистрация</a></li>
			{% endif %}
		</ul>
		<div class="clear"></div>
	</div>
{% endblock mainmenu %}


	<table class="table-content" border=0 cellpadding="0" cellspacing="0">
	<tr>
		<td valign="top" class="left-chapters">
			<ul id="leftchapters">
				{% if cat_selected == 0 %}
					<li class="selected">Все категории</li>
				{% else %}
					<li><a href="{% url 'index' %}">Все категории</a></li>
				{% endif %}

				{% show_categories cat_selected %}

				<li>{% show_tags %}</li>
			</ul>
		</td>


		<td valign="top" class="content">

			{% block breadcrumbs %}
			{% endblock %}

		<div class="content-text">
		{% block content %} {% endblock %}
		</div>


{% block navigation %} {% endblock %}

		</td>
	</tr>
	</table>
</td>
</tr>
	<tr>
		<td valign=top>
		<div id="footer">
			<p>&copy; 2024 Частичное или полное копирование информации с данного сайта для распространения на других ресурсах, в том числе и бумажных, строго запрещено.</p>
		</div>
		</td>
	</tr>
</table>


</body>
</html>